# This workflow will download a prebuilt Ruby version, install dependencies and
# run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

"on":
  push:
    # branches: [master]
  # pull_request:
  #   branches: [master]
  # schedule:
  #   - cron: '16 4 12 * *'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # ruby: ["2.7", "3.0", "3.1"]
        ruby: ["3.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Install non-ruby dependencies
        run: |
          sudo apt-get update

          sudo apt-get remove libunwind-14-dev           # Prevent conflict with libunwind-dev, needed by libgstreamer1.0-dev

          sudo apt-get install libgtk-3-dev \
            libgstreamer1.0-dev \
            libyaz-dev \
            libgoocanvas-2.0-dev \
            intltool \
            gconf2 \
            at-spi2-core \
            gstreamer1.0-plugins-good \
            pulseaudio \
            xvfb \
            yaru-theme-icon

      - uses: actions/checkout@v3
        with:
          repository: "ruby-gnome/ruby-gnome"
          path: "ruby-gnome"
      - name: Apply a patch
        run: |
          cd ruby-gnome
          patch -p1 -i ../ruby-gnome.diff
          git config --global user.email "kou@cozmixng.org"
          git config --global user.name "Sutou Kouhei"
          git add .
          git commit -m 'apply a patch'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run unit tests
        run: SEGV_HANDLER_GDB_PATH=+ xvfb-run bundle exec rake spec:unit

      - name: Run end-to-end tests in a dbus session
        run: xvfb-run dbus-run-session bundle exec rake spec:end_to_end

  # rubocop:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install non-ruby dependencies
  #       run: |
  #         sudo apt-get update

  #         sudo apt-get remove libunwind-14-dev           # Prevent conflict with libunwind-dev, needed by libgstreamer1.0-dev

  #         sudo apt-get install libgtk-3-dev              # Needed for gtk3 gem
  #         sudo apt-get install libgstreamer1.0-dev       # Needed for gstreamer gem
  #         sudo apt-get install libyaz-dev                # Needed for zoom gem

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true

  #     - name: Run RuboCop
  #       run: bundle exec rubocop -P
